language: php

rvm:
 - 5.6

before_script:
 - php composer-setup.php
 - php composer.phar install
 - php composer.phar update
 - mkdir protected/runtime

script:
 - cd protected/tests
 - ../../vendor/bin/phpunit --verbose unit